In [1]:
import numpy as np
from ainsworth_ieee import *
from read_image import image_array

In [2]:
import numpy as np
from tqdm import tqdm
from numpy.linalg import LinAlgError
np.set_printoptions(linewidth=1000)

def get_covariance(hh, hv, vh, vv):
    C = np.zeros((4,4), dtype=np.complex64)
    C[0,0] = np.mean(hh * np.conj(hh))
    C[0,1] = np.mean(hh * np.conj(hv))
    C[0,2] = np.mean(hh * np.conj(vh))
    C[0,3] = np.mean(hh * np.conj(vv))

    C[1,0] = np.mean(hv * np.conj(hh))
    C[1,1] = np.mean(hv * np.conj(hv))
    C[1,2] = np.mean(hv * np.conj(vh))
    C[1,3] = np.mean(hv * np.conj(vv))

    C[2,0] = np.mean(vh * np.conj(hh))
    C[2,1] = np.mean(vh * np.conj(hv))
    C[2,2] = np.mean(vh * np.conj(vh))
    C[2,3] = np.mean(vh * np.conj(vv))

    C[3,0] = np.mean(vv * np.conj(hh))
    C[3,1] = np.mean(vv * np.conj(hv))
    C[3,2] = np.mean(vv * np.conj(vh))
    C[3,3] = np.mean(vv * np.conj(vv))

    return C

def compute_sigma_1_matrix(u, v, w, z, alpha):
    sqrt_alpha = np.sqrt(alpha)
    arr = np.array([[1, -w, -v, v*w],
                    [-u / sqrt_alpha, 1 / sqrt_alpha, (u*v) / sqrt_alpha, -v / sqrt_alpha],
                    [-z / sqrt_alpha, (w*z) / sqrt_alpha, sqrt_alpha, -w / sqrt_alpha],
                    [(u*z), -z, -u, 1]])

    multiplier = 1 / (((u*w) - 1) * ((v*z)-1))  
    return arr * multiplier

def compute_alpha(covariance):
    x = covariance[1,2] / np.abs(covariance[1,2])
    y = np.sqrt(np.abs(covariance[1,1] / covariance[2,2]))
    return x*y

def compute_A(covariance):
     return (covariance[1,0] + covariance[2,0]) / 2

def compute_B(covariance):
     return (covariance[1,3] + covariance[2,3]) / 2

def compute_X_matrix(covariance, A, B):
    x_matrix = np.array([
          [covariance[2,0] - A],
          [covariance[1,0] - A],
          [covariance[2,3] - B], 
          [covariance[1,3] - B]])
    
    return x_matrix

def compute_zeta_matrix(covariance):
    zeta_matrix = np.array([
          [0, 0, covariance[3,0], covariance[0,0]],
          [covariance[0,0], covariance[3,0], 0, 0],
          [0, 0, covariance[3,3], covariance[0,3]],
          [covariance[0,3], covariance[3,3], 0, 0]])
    
    return zeta_matrix

def compute_tau_matrix(covariance):
    tau_matrix = np.array([
          [0, covariance[2,2], covariance[2,1], 0],
          [0, covariance[1,2], covariance[1,1], 0],
          [covariance[2,2], 0, 0, covariance[2,1]],
          [covariance[1,2], 0, 0, covariance[1,1]]])
    
    return tau_matrix



def parameter_updates(x, zeta, tau):
    X_Matrix_Need = np.concatenate([np.real(x), np.imag(x)])

    Zeta_Tau_Matrix_Need = np.concatenate([np.concatenate([np.real(zeta + tau), -1 * np.imag(zeta - tau)], axis=1),
                                           np.concatenate([np.imag(zeta + tau), np.real(zeta - tau)], axis=1)])

    delta_Solve = np.linalg.inv(Zeta_Tau_Matrix_Need) @ X_Matrix_Need

    delta_u = delta_Solve[0] + 1j * delta_Solve[4]
    delta_v = delta_Solve[1] + 1j * delta_Solve[5]
    delta_w = delta_Solve[2] + 1j * delta_Solve[6]
    delta_z = delta_Solve[3] + 1j * delta_Solve[7]

    return delta_u, delta_v, delta_w, delta_z


def ainswoth_cal(covar):
    u = 0
    v = 0
    w = 0
    z = 0
    gamma = 100
    tolerance = 1e-8
    i_iter = 0
    alpha = compute_alpha(covar)

    while i_iter < 12:
        sigma_1_matrix_i = compute_sigma_1_matrix(u, v, w, z, alpha)

        covariance_i = sigma_1_matrix_i @ covar @ np.conj(sigma_1_matrix_i).T
        A = compute_A(covariance_i)
        B = compute_B(covariance_i)

        X = compute_X_matrix(covariance_i, A, B)
        zeta = compute_zeta_matrix(covariance_i)
        tau = compute_tau_matrix(covariance_i)
        delta_u, delta_v, delta_w, delta_z = parameter_updates(X, zeta, tau)
        alpha_i = compute_alpha(covariance_i)

        u = (u + delta_u / np.sqrt(alpha))[0]
        v = (v + delta_v / np.sqrt(alpha))[0]
        w = (w + delta_w * np.sqrt(alpha))[0]
        z = (z + delta_z * np.sqrt(alpha))[0]
        alpha = alpha * alpha_i

        gamma = (max(abs(u), abs(v), abs(w), abs(z)))
        i_iter = i_iter + 1
    
    return sigma_1_matrix_i

In [ ]:
window_size_x,window_size_y = 3,3
x,y = 3,3
HH = image_array(r'C:\Users\Vision IAS\Desktop\work\SAR\Output\HH_uncalibrated.tiff')[:x,:y]
HV = image_array(r'C:\Users\Vision IAS\Desktop\work\SAR\Output\HV_uncalibrated.tiff')[:x,:y]
VH = image_array(r'C:\Users\Vision IAS\Desktop\work\SAR\Output\VH_uncalibrated.tiff')[:x,:y]
VV = image_array(r'C:\Users\Vision IAS\Desktop\work\SAR\Output\VV_uncalibrated.tiff')[:x,:y]

def sliding_window(HH, HV, VH, VV, window_size_x, window_size_y):
    rows, cols = HH.shape
    for i in range(0, rows, window_size_y):
        for j in range(0, cols, window_size_x):  
            if i + window_size_y <= rows and j + window_size_x <= cols:
                hh = HH[i:i+window_size_y, j:j+window_size_x]
                hv = HV[i:i+window_size_y, j:j+window_size_x]
                vh = VH[i:i+window_size_y, j:j+window_size_x]
                vv = VV[i:i+window_size_y, j:j+window_size_x]
                yield hh, hv, vh, vv

pbar = tqdm(total = x * (x//window_size_x), desc = 'Computing Parameters', unit = ' windows')
for a,b,c,d in sliding_window(HH, HV, VH, VV, window_size_x, window_size_y):
    cov = get_covariance(a,b,c,d)
    cal_mat = ainswoth_cal(cov)
    true = cal_mat @ np.array([[a,b,c,d]]).T
    pbar.update(1)
pbar.close()

Computing Parameters:  33%|███▎      | 1/3 [00:00<00:00, 104.98 windows/s]

[[-0.00690127-0.02906244j  0.04874293-0.01083722j  0.09196864-0.0122088j ]
 [-0.01627338-0.00610797j  0.01897904+0.04147513j  0.06223828+0.06260392j]
 [-0.05928316-0.01689963j -0.02648653+0.03150305j -0.00076173+0.05830637j]]


In [19]:
HH = true[:, :, 0, 0] 
HH

array([[-0.00660605-0.02864918j, -0.01587002-0.00535819j, -0.05842006-0.0175299j ],
       [ 0.04842327-0.00992163j,  0.01842302+0.04170095j, -0.02646842+0.03083595j],
       [ 0.09194526-0.01057932j,  0.06113858+0.06333135j, -0.00168575+0.05764587j]])

In [29]:
HV = true[:, :, 1, 0] 
HV

array([[-4.73362362e-04+1.16914239e-03j, -5.38015067e-03-8.68276963e-05j, -3.87790653e-03+4.21604213e-03j],
       [-2.96562814e-03+1.31390551e-03j,  5.38722168e-05-1.03262548e-03j,  2.94886848e-04+4.44152500e-03j],
       [-6.90224462e-03+3.08749398e-03j, -8.05982607e-04-4.20667699e-03j,  6.93425956e-03-1.36494133e-03j]])

In [28]:
VH = true[:, :, 2, 0]
VH

array([[ 0.00163994+0.00279656j,  0.00284342+0.00145377j, -0.00312406+0.00270138j],
       [-0.00435081+0.00541721j,  0.00030679-0.00184563j,  0.00041054+0.00257131j],
       [-0.00617701+0.00507575j, -0.00194044-0.00439725j,  0.00453484-0.00246506j]])

In [23]:
VV = true[:, :, 3, 0] 
VV

array([[ 0.00304924-0.03568966j, -0.01101555+0.00239535j, -0.06017697-0.00595462j],
       [ 0.06169926-0.03227201j,  0.03636025+0.03068926j, -0.01903784+0.03706011j],
       [ 0.10715839-0.04298058j,  0.08077424+0.03993705j,  0.0055849 +0.05411345j]])